djMany2Many/djMany2Many/urls.py
from django.contrib import admin
from django.urls import path
from WebApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dlist/',views.DList),
]

djMany2Many/WebApp/models.py
from django.db import models
# Create your models here.
class Driver(models.Model):
    dname=models.CharField(max_length=255)
    def __str__(self):
        return self.dname
class Car(models.Model):
    cname=models.CharField(max_length=233)
    drivers=models.ManyToManyField(Driver,)
    def __str__(self):
        return self.cname

djMany2Many/WebApp/views.py
from django.shortcuts import render
from WebApp.models import Driver
# Create your views here.
def DList(request):
    items=Driver.objects.all()
    return render(request,'MyApp/Many.html',{'items':items})

djMany2Many/templates/MyApp/Many.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <h2>ManyToManyDBRelations.....!!</h2>
</nav>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            {% for x in items %}
            <h2>{{ x.dname }}</h2>
            {% for car in x.car_set.all %}
            {{ car.cname }} <br>
            {%endfor%}
            {%endfor%}
        </div>
        <div class="col-md-6">
    </div>
        </div>
</div>
</body>
</html>